@startuml

queue "Queue" #Cyan
queue ResponseQueue as "Tmp ResponseQueue" #Cyan
node Client #Orchid
node JMSRequestSink #Khaki
node JMSRequestProxy #Khaki
node "RequestSink Implementation" #Orchid
interface Topic #LightGreen

Client -> JMSRequestSink
JMSRequestSink --> Queue
JMSRequestSink ..> Topic : broadcast

Queue -> JMSRequestProxy
Topic ..> JMSRequestProxy
JMSRequestProxy -> "RequestSink Implementation"
JMSRequestProxy <.. "RequestSink Implementation" : RequestContext.addResponse()

JMSRequestProxy ..> ResponseQueue
ResponseQueue .> JMSRequestSink
JMSRequestSink ..> Client : RequestContext.addResponse()

@enduml